const prettier = require("eslint-config-prettier");

module.exports = [
  {
    ignores: ["node_modules/", "temp/", "*.json", ".env"],
  },
  {
    files: ["server/**/*.js", "server.js", "src/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        // Node.js globals
        require: "readonly",
        module: "readonly",
        __dirname: "readonly",
        process: "readonly",
        exports: "writable",
        Buffer: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        // Browser globals (for game.js)
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        fetch: "readonly",
        WebSocket: "readonly",
        Image: "readonly",
        Audio: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        performance: "readonly",
        canvas: "writable",
        ctx: "writable",
        HTMLCanvasElement: "readonly",
        CanvasRenderingContext2D: "readonly",
        TouchEvent: "readonly",
        PointerEvent: "readonly",
        history: "readonly",
        location: "readonly",
        localStorage: "readonly",
        crypto: "readonly",
        self: "readonly",
        console: "readonly",
        Promise: "readonly",
        FileReader: "readonly",
        customElements: "readonly",
        CustomEvent: "readonly",
        MutationObserver: "readonly",
        ResizeObserver: "readonly",
        Blob: "readonly",
        URL: "readonly",
        atob: "readonly",
        btoa: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-undef": "off",
      "no-constant-condition": "warn",
      "no-empty": "warn",
      "no-irregular-whitespace": "warn",
      "no-redeclare": "warn",
      "no-control-regex": "off",
      "no-prototype-builtins": "off",
      "no-extra-semi": "warn",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-unreachable": "warn",
      "valid-typeof": "error",
      "getter-return": "error",
      "use-isnan": "error",
      eqeqeq: ["warn", "smart"],
      curly: ["warn", "multi-line"],
      "dot-notation": "warn",
      ...prettier.rules,
    },
  },
  {
    files: ["server/**/*.test.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        process: "readonly",
        console: "readonly",
        Promise: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      ...prettier.rules,
    },
  },
];
